# Generated by Django 2.2.3 on 2019-07-01 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reforms', '0002_add_states'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='id',
        ),
        migrations.AlterField(
            model_name='state',
            name='abbreviation',
            field=models.CharField(max_length=2, primary_key=True, serialize=False),
        ),
    ]
