# Generated by Django 2.2.3 on 2019-07-01 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("reforms", "0005_comment")]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="state",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="comments",
                to="reforms.State",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="comment",
            name="from_email",
            field=models.EmailField(max_length=254, verbose_name="Email"),
        ),
    ]
