# Generated by Django 2.2.3 on 2019-07-03 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("reforms", "0007_state_latest_test_url")]

    operations = [
        migrations.AddField(
            model_name="state",
            name="gov_control",
            field=models.CharField(blank=True, max_length=300),
        )
    ]
