---
- name: Install reform
  hosts: reform reform-auto
  user: ubuntu
  become: yes
  roles:
    - role: django-uwsgi-nginx
      vars:
        - git_repository: https://github.com/OpenPrecincts/reform-microsite.git
          user: reform
          directory: reform
          wsgi_module: web.wsgi
          domain_name: reform.openprecincts.org
          celery: false
    - role: reform
      vars:
        - user: reform
