on: push
name: Deploy On Push
jobs:
  deployMaster:
    name: Deploy Master
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Only On Master
      uses: actions/bin/filter@master
      with:
        args: branch master
    - name: ./ansible-action
      uses: ./ansible-action
      env:
        ANSIBLE_GALAXY_FILE: ansible/requirements.yml
        ANSIBLE_HOST_KEY_CHECKING: "False"
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
        SMTP_USER: ${{ secrets.SMTP_USER }}
        SSH_KEY: ${{ secrets.SSH_KEY }}
      with:
        args: ansible/reform.yml -i ansible/inventory -l reform-auto
